baseurl                  = "https://ecstatic-sinoussi-95242d.netlify.app"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Zero-Sum"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    showDate             = true
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "zero-sum's website created by [@qporest](https://www.qporest.com) using [Hugo](https://gohugo.io/) and modified theme [Sam](https://github.com/victoriadrake/hugo-theme-sam/)"

# Metadata for Open Graph and Twitter
    description          = "Punk rock band from OH."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "zero-sum"
    # rss                = ""

[[params.mainMenu]]
    link = "news"
    text = "news"

[[params.mainMenu]]
    link = "gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "about"
    text = "about+epk"

[[params.mainMenu]]
    link = "contact"
    text = "contact"

[imaging]
    quality = 75
